### ISSUE TITLE
error loading chunks w/villagers in in 1.20.6; villagers don't get loaded in

### ISSUE THREAD

**Issue by cheesykatie** [enjarai/smart-villagers-follow-emeralds#2]
I was using this mod on 1.20.1 (in a world that had been updated several times for a couple years) and updated my server to 1.20.6 on the 2nd of May. I downloaded and added this mod back again on the 4th. I was in a hurry and must have forgotten to check the console. When I logged in today, none of the world's villagers had been loaded in.

I checked the console and saw errors. Stopped the server, downloaded the backup, deleted the mod and restarted the server to see if it would read them from file this time. Thankfully it did, and nothing was actually deleted or overwritten (all villagers accounted for).

Other mods in my mods folder:
Fabric API (fabric-api-0.97.8+1.20.6.jar)
Carpet by gnembon (fabric-carpet-1.20.6-1.4.141+v240429.jar)
Lithium by jellysquid (lithium-fabric-mc1.20.6-0.12.3.jar)
Simple Voice Chat by henkelmax (voicechat-fabric-1.20.6-2.5.12.jar)

Here's a snippet from the log; all the errors looked like this:

```
[10:38:04] [Server thread/ERROR]: Failed to read chunk [1, -20]
java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: 'void net.minecraft.class_5760.<init>(net.minecraft.class_1856)'
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_3846.method_16907(class_3846.java:91) ~[server-intermediary.jar:?]
	at net.minecraft.class_3846.method_16900(class_3846.java:146) ~[server-intermediary.jar:?]
	at net.minecraft.class_3846.run(class_3846.java:102) ~[server-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:162) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:841) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:168) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:136) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:823) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:817) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:145) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:792) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:696) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:275) ~[server-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.NoSuchMethodError: 'void net.minecraft.class_5760.<init>(net.minecraft.class_1856)'
	at dev.enjarai.svfe.ModSensorTypes.lambda$static$0(ModSensorTypes.java:13) ~[smart-villagers-follow-emeralds-1.0.0.jar:?]
	at net.minecraft.class_4149.method_19102(class_4149.java:53) ~[server-intermediary.jar:?]
	at net.minecraft.class_4095.<init>(class_4095.java:147) ~[server-intermediary.jar:?]
	at net.minecraft.class_4095$1.decode(class_4095.java:94) ~[server-intermediary.jar:?]
	at com.mojang.serialization.MapDecoder.lambda$compressedDecode$1(MapDecoder.java:52) ~[datafixerupper-7.0.14.jar:?]
	at com.mojang.serialization.DataResult$Success.flatMap(DataResult.java:194) ~[datafixerupper-7.0.14.jar:?]
	at com.mojang.serialization.MapDecoder.compressedDecode(MapDecoder.java:52) ~[datafixerupper-7.0.14.jar:?]
	at com.mojang.serialization.MapCodec$MapCodecCodec.decode(MapCodec.java:158) ~[datafixerupper-7.0.14.jar:?]
	at com.mojang.serialization.Decoder.parse(Decoder.java:18) ~[datafixerupper-7.0.14.jar:?]
	at com.mojang.serialization.codecs.FieldDecoder.decode(FieldDecoder.java:29) ~[datafixerupper-7.0.14.jar:?]
	at com.mojang.serialization.MapCodec$2.decode(MapCodec.java:77) ~[datafixerupper-7.0.14.jar:?]
	at com.mojang.serialization.MapDecoder.lambda$compressedDecode$1(MapDecoder.java:52) ~[datafixerupper-7.0.14.jar:?]
	at com.mojang.serialization.DataResult$Success.flatMap(DataResult.java:194) ~[datafixerupper-7.0.14.jar:?]
	at com.mojang.serialization.MapDecoder.compressedDecode(MapDecoder.java:52) ~[datafixerupper-7.0.14.jar:?]
	at com.mojang.serialization.MapCodec$MapCodecCodec.decode(MapCodec.java:158) ~[datafixerupper-7.0.14.jar:?]
	at com.mojang.serialization.Decoder.decode(Decoder.java:22) ~[datafixerupper-7.0.14.jar:?]
	at com.mojang.serialization.Decoder.parse(Decoder.java:26) ~[datafixerupper-7.0.14.jar:?]
	at net.minecraft.class_4095$class_5303.method_28335(class_4095.java:64) ~[server-intermediary.jar:?]
	at net.minecraft.class_1646.method_18867(class_1646.java:221) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.<init>(class_1309.java:272) ~[server-intermediary.jar:?]
	at net.minecraft.class_1308.<init>(class_1308.java:152) ~[server-intermediary.jar:?]
	at net.minecraft.class_1314.<init>(class_1314.java:17) ~[server-intermediary.jar:?]
	at net.minecraft.class_1296.<init>(class_1296.java:29) ~[server-intermediary.jar:?]
	at net.minecraft.class_3988.<init>(class_3988.java:58) ~[server-intermediary.jar:?]
	at net.minecraft.class_1646.<init>(class_1646.java:201) ~[server-intermediary.jar:?]
	at net.minecraft.class_1646.<init>(class_1646.java:197) ~[server-intermediary.jar:?]
	at net.minecraft.class_1299.method_5883(class_1299.java:552) ~[server-intermediary.jar:?]
	at net.minecraft.class_1299.method_17846(class_1299.java:556) ~[server-intermediary.jar:?]
	at java.base/java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.minecraft.class_1299.method_5892(class_1299.java:556) ~[server-intermediary.jar:?]
	at net.minecraft.class_1299.method_17848(class_1299.java:644) ~[server-intermediary.jar:?]
	at net.minecraft.class_1299.method_17842(class_1299.java:595) ~[server-intermediary.jar:?]
	at net.minecraft.class_1299$1.method_31490(class_1299.java:618) ~[server-intermediary.jar:?]
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1950) ~[?:?]
	at net.minecraft.class_1299$1.tryAdvance(class_1299.java:617) ~[server-intermediary.jar:?]
	at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:332) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at net.minecraft.class_5565.method_31731(class_5565.java:71) ~[server-intermediary.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	... 17 more

```

**Comment by enjarai** [comment]
I see, I hadn't expected villager code to change with 1.20.5, but I guess it did. I'll work on a fix.
